baseURL: "https://melisa.org.pl/"
languageCode: "pl-PL"
title: "Melisa Retreat"
theme: "zen"

params:
    feedlinks: false
    podcast:
        image: image/isabella_Relaxation.jpg
    searchform: true
    logo: false
    mobileMenu: true
    sidebar: false

languages:
    en:
        weight: 3
        languageName: "English"
        languageCode: "en-GB"
    de:
        weight: 2
        languageName: "Deutsch"
        languageCode: "de-AT"
    pl:
        weight: 1
        languageName: "Polski"
        title: "Melisa"

DefaultContentLanguage: pl
defaultContentLanguageInSubdir: true
