baseURL: "https://melisaretreat.at/"
languageCode: "de-AT"
title: "Melisa Retreat"
disableKinds:
- taxonomy
- terms
taxonomy:
  category:
    - categories
  tag:
    - tags
ignoreErrors:
  - error-disable-taxonomy

params:
  feedlinks: false
  logo: false
  mobileMenu: true
  sidebar: false
  mainSections:
  - events
  dateformat: 2006-01-02

DefaultContentLanguage: de

module:
  hugoVersions:
    min: 0.56.0
  imports:
  - path: github.com/frjo/hugo-theme-zen
